### ISSUE TITLE
sometimes refreshing impairs folding

### ISSUE THREAD

**Issue by mcadenhe** [dmotz/oriDomi#23]
total newbie.

sometimes the oridomi effect works perfect upon 1st loading. if i refresh the page though, all of a sudden the handle to fold the image doesn't appear when mousing over parts of the image, but only around the edges. if i refresh a few more times it seems to work perfect again and the handle appears anytime i mouseover any of the area of the image.

i'm confused why it would work sometimes but then doesn't work.

**Comment by dmotz** [comment]
This Chrome bug has been finally fixed: https://code.google.com/p/chromium/issues/detail?id=126479#c34
