### ISSUE TITLE
Semantic document outline and accessibility

### ISSUE THREAD

**Issue by jaydenseric** [dmotz/oriDomi#34]
oriDomi creates many copies of HMTL elements to create the fold effect. This can really bloat the semantic document outline with copies of headings in particular, potentially causing headaches for accessibility (see screenshot).

Could this be mitigated by applying an attribute such as `aria-hidden="true"` to all the duplicate layers?

![oriDomi document outline screenshot](https://cloud.githubusercontent.com/assets/1754873/3143361/718458c8-e9f6-11e3-953c-3d41a90d6652.png)

**Comment by getsetbro** [comment]
![screenshot_2015-08-22-08-56-14](https://cloud.githubusercontent.com/assets/442793/9424269/12ecd6f8-48ac-11e5-965b-6039b4edca05.png)
Is there a fix for the repetition in search results!

**Comment by dmotz** [comment]
@getsetbro This happens if the crawler runs client side scripts and indexes the modified DOM. I don't know of any way to conditionally exclude content from a crawler. If you do, let me know.

**Comment by getsetbro** [comment]
Does ordomi use the H1? I was thinking for my site I need to add the markup
that seo is looking for. Then Google would show that instead.
