### ISSUE TITLE
oridomi worse now in android lollipop?

### ISSUE THREAD

**Issue by getsetbro** [dmotz/oriDomi#44]
I'm not sure what android has changed but it used to work better.
![screenshot_2015-07-15-13-18-57](https://cloud.githubusercontent.com/assets/442793/8706213/2f5a5f66-2af4-11e5-8338-503d9ac02ee1.png)
Any ideas?

**Comment by dmotz** [comment]
Just tested on a phone running Lollipop, didn't see this behavior.

Looks like the GPU is messing up the textures. Do you see this happen on other sites using 3D CSS transforms? Maybe try restarting the phone.

**Comment by getsetbro** [comment]
Okay, I get the above issue on a Moto X (1st Gen) but not a Nexus 4.

**Comment by dmotz** [comment]
I would report it to the Chrome devs as a rendering regression.
