### ISSUE TITLE
how to remove oriDomi by click?

### ISSUE THREAD

**Issue by petrospap** [dmotz/oriDomi#45]
Hello!
I use oridomi by your example with jquery i.e

```
$('#startButton').click(function(){
var $folded = $('.paper').oriDomi({/* options object */});
// when using jQuery, iterate OriDomi methods over multiple elements like this:
$folded.oriDomi('accordion', 20);
// to access the OriDomi instance at the top of the jQuery selection directly:
var folded = $folded.oriDomi(true);
});
```

How to remove oridomi by click?
```
$('#cancelButton').click(function(){
// remove oridomi?
});
```

Sorry for the noob question!

**Comment by dmotz** [comment]
To simply reset the element to its flat state you can call `folded.reset()`.

To destroy OriDomi's modifications entirely and restore the original element, call `folded.destroy()`.

**Comment by petrospap** [comment]
Thanks dmotz, but I got TypeError: $folded.destroy is not a function, 
reset the same

**Comment by petrospap** [comment]
Ohh my bad i write it with $, removed and all is OK, thanks
