### ISSUE TITLE
Center a OriDomi element?

### ISSUE THREAD

**Issue by jedrichards** [dmotz/oriDomi#46]
Thanks for your work on this, its a beautiful effect!

Is it possible to horizontally center a oridomi element somehow, even while part folded? At the moment it seems like the width of the element stays at the unfolded original value, so when folded the whole element is off to the side. Any workarounds?

Ty!

**Comment by dmotz** [comment]
Since CSS transforms don't affect DOM flow, the container's size doesn't change when folding. You could use a callback and manually offset the OriDomi element based on the fold angle, but it'll be tricky since the width will depend on the perspective and effect settings.
