### ISSUE TITLE
Blurred text contents

### ISSUE THREAD

**Issue by fede91it** [dmotz/oriDomi#49]
When I apply oriDomi to a box containing text, this gets blurred and poorly readable.

**Comment by dmotz** [comment]
Do you have a demo link or screenshots?

**Comment by Campbellding** [comment]
I have the same problem. I think this is the webkit rendering issue, the blur will be reduced if you view with firefox. The demo of this can be found on http://oridomi.com/ (third row, second column)
![image](https://cloud.githubusercontent.com/assets/4064310/15347248/3a4b967c-1d03-11e6-9b17-0520f114e381.png)

**Comment by dmotz** [comment]
This is dependent on your browser's rendering engine and OS, but one thing you can try to mitigate it is by making your containing element larger than it needs to be and then using a scale transform to return it to the desired size. 

With CSS 3D transforms, when the texture of the element is moved toward the viewer on the Z axis, bitmap artifacts can become apparent.
