### ISSUE TITLE
Targeting multiple elements, or individual elements within .each()

### ISSUE THREAD

**Issue by lesliecdub** [dmotz/oriDomi#50]
Hi there! Great plugin.

I have several elements on the page using the same class that, on hover, I would like to apply an oriDomi effect to. I currently have the hover event set up inside a .each() that loops through all of the elements with the class in question.

Unfortunately, it seems that oriDomi only targets the first DOM element that matches the selector provided. Is there a way to target a specific element via the selector (i.e., $(this).find('.my-element')), or to target all elements of a specific class name?

**Comment by dmotz** [comment]
If you're already using an `each` loop, try something like this:

```javascript
$('.some-class').each(function() { 
  var $this = $(this).oriDomi()
  $this.hover(function() {
    $this.oriDomi('accordion', 50)
  })
})
```

(Replacing the effect call with the one you want.)

**Comment by lesliecdub** [comment]
Thanks @dmotz! That did the trick.
